import Tests.Test
import Tests.TestDataLoader
import Tests.TestModdedGPT
import Tests.TestCheckpoint
import Tests.TestModelIO
import Tests.TestPipeline
import Tests.TestAutoGrad
import Tests.TestManifoldMuon
import Tests.TestDualOptimizerDispatch
import Tests.TestModularManifold
import Tests.TestMetricFactor
import Tests.TestRiemannianSGD
import Tests.TestRiemannianNanoGPT
import Tests.TestGPUAutoGrad
import Tests.TestADJaxprLike
import Tests.TestADJaxprLikeExtract
import Tests.TestADTensorStructSchema
import Tests.TestADTensorStructFlatten
import Tests.TestADFrontendSignature
import Tests.TestADFrontendElab
import Tests.TestADGraphaxAlphaGradParity
import Tests.TestADGraphaxAlphaGradCoverageGate
import Tests.TestADSparse
import Tests.TestADElimGraph
import Tests.TestADElimOrderPolicy
import Tests.TestADElimFromJaxpr
import Tests.TestADElimLowering
import Tests.TestADElimAlphaGradMctx
import Tests.TestAlphaGradPortExamples
import Tests.TestModularNorm
import Tests.TestMctxImport
import Tests.TestMctxSeqHalving
import Tests.TestMctxQTransforms
import Tests.TestMctxPolicies
import Tests.TestMctxTree
import Tests.TestMctx
import Tests.TestMctxBatched
import Tests.TestMctxDag
import Tests.TestDiffEq
import Tests.TestDiffEqEventTreeParity
import Tests.TestDiffEqMilsteinAutodiffParity
import Tests.TestDiffEqSDEOrderParity
import Tests.TestDiffEqUnderdampedOrderParity
import Tests.TestDiffEqWeakStats
import Tests.TestDiffEqWeakStatsParity2
import Tests.TestDiffEqAdjoint
import Tests.TestDiffEqAdjointCore
import Tests.TestGPUDSL
import Tests.TestGPUKernels
import Tests.TestNanoChatTokens
import Tests.TestNanoChatTasks
import Tests.TestQwen3ASR
import Tests.TestSileroVAD
import Tests.TestQwen3Model
import Tests.TestQwen3TTS
import Tests.TestQwen35Model
import Tests.TestQwen35Multimodal
import Tests.TestQwen35Pretrained
import Tests.TestQwen25OmniPretrained
import Tests.TestSafeTensorsTypeProvider
import Tests.TestSafeTensorsTypeProviderErrors

-- Note: `Tests.TestBranchingFlows` is currently routed through
-- `TestsExperimental.lean` until `Tyr/Model/BranchingFlows.lean` is stabilized.
