import Init.Omega

/-!
# Generic shape and extent obligations

This module captures the shape-side facts used by lowering passes:

- an affine subrange is inside a shape dimension,
- every index generated by that subrange is in bounds,
- non-unit extents match when scalar dimensions are ignored,
- static extents satisfy divisibility/alignment constraints.

The definitions are not tied to TVM, TIR, or a GPU backend.
-/

namespace Tyr.ShapeSync

/-- A one-dimensional affine range `[min, min + extent)`. -/
structure DimRange where
  min : Int
  extent : Int
deriving Repr, BEq, DecidableEq

namespace DimRange

def zeroExtent (extent : Int) : DimRange :=
  { min := 0, extent }

/-- `r` is a valid range contained in a dimension of size `shape`. -/
def WithinShape (r : DimRange) (shape : Int) : Prop :=
  0 <= r.min ∧ 0 <= r.extent ∧ r.min + r.extent <= shape

/-- `i` is a local index in `r`. -/
def ContainsLocal (r : DimRange) (i : Int) : Prop :=
  0 <= i ∧ i < r.extent

/-- Translate a local range index to the global dimension index. -/
def globalIndex (r : DimRange) (i : Int) : Int :=
  r.min + i

theorem local_index_in_shape {r : DimRange} {shape i : Int}
    (hr : r.WithinShape shape) (hi : r.ContainsLocal i) :
    0 <= r.globalIndex i ∧ r.globalIndex i < shape := by
  unfold WithinShape ContainsLocal globalIndex at *
  omega

theorem range_upper_bound {r : DimRange} {shape : Int}
    (hr : r.WithinShape shape) : r.min + r.extent <= shape := by
  exact hr.2.2

theorem extent_nonnegative {r : DimRange} {shape : Int}
    (hr : r.WithinShape shape) : 0 <= r.extent := by
  exact hr.2.1

end DimRange

/--
Drop singleton dimensions and check that each remaining source extent fits in
the matched base extent. This mirrors the lowering pattern that skips extent-1
dimensions before choosing loop domains.
-/
partial def nonUnitExtentsFit : List Nat → List Nat → Bool
  | [], [] => true
  | [], src => src.all (fun x => x == 1)
  | base, [] => base.all (fun x => x == 1)
  | b :: bs, s :: ss =>
      if b == 1 then
        nonUnitExtentsFit bs (s :: ss)
      else if s == 1 then
        nonUnitExtentsFit (b :: bs) ss
      else
        s <= b && nonUnitExtentsFit bs ss

def NonUnitExtentsFit (base src : List Nat) : Prop :=
  nonUnitExtentsFit base src = true

def DivisibleBy (n d : Nat) : Prop :=
  d != 0 ∧ n % d = 0

def MultipleOf (n d : Nat) : Prop :=
  DivisibleBy n d

instance (base src : List Nat) : Decidable (NonUnitExtentsFit base src) := by
  unfold NonUnitExtentsFit
  infer_instance

instance (n d : Nat) : Decidable (DivisibleBy n d) := by
  unfold DivisibleBy
  infer_instance

theorem divisible_refl {d : Nat} (h : d != 0) : DivisibleBy d d := by
  unfold DivisibleBy
  exact ⟨h, Nat.mod_self d⟩

theorem divisible_mul_left (k d : Nat) (h : d != 0) : DivisibleBy (k * d) d := by
  unfold DivisibleBy
  exact ⟨h, Nat.mul_mod_left k d⟩

inductive ShapeObligation where
| rangeWithinShape (range : DimRange) (shape : Int)
| localIndexInBounds (range : DimRange) (shape index : Int)
| nonUnitExtentsFit (base src : List Nat)
| divisible (n d : Nat)
deriving Repr, BEq, DecidableEq

namespace ShapeObligation

def Valid : ShapeObligation → Prop
  | .rangeWithinShape range shape => range.WithinShape shape
  | .localIndexInBounds range shape index =>
      range.WithinShape shape →
      range.ContainsLocal index →
      0 <= range.globalIndex index ∧ range.globalIndex index < shape
  | .nonUnitExtentsFit base src => NonUnitExtentsFit base src
  | .divisible n d => DivisibleBy n d

instance (obl : ShapeObligation) : Decidable obl.Valid := by
  cases obl <;>
    unfold Valid DimRange.WithinShape DimRange.ContainsLocal
      NonUnitExtentsFit DivisibleBy <;>
    infer_instance

end ShapeObligation

end Tyr.ShapeSync
