import Tyr.GPU.Types
import Tyr.GPU.Codegen.Var
import Tyr.GPU.Codegen.IR

/-!
# Tyr.GPU.Codegen.Monad

`Tyr.GPU.Codegen.Monad` provides the stateful kernel-construction API.
`KernelM` accumulates IR statements while tracking fresh variable IDs,
target architecture, and shared-memory usage.

This layer turns imperative-looking `do` notation into immutable IR:

- `freshVar` allocates symbolic names,
- `emit` appends `KStmt`,
- `buildKernelM` seals the final `Kernel`.

Most user-facing DSL functions in `Ops` and `Notation` are thin wrappers over
this monad.
-/

namespace Tyr.GPU.Codegen

open Tyr.GPU

/-- Kernel building state -/
structure KernelState where
  /-- Next available variable ID -/
  nextId : Nat := 0
  /-- Accumulated kernel statements -/
  body : Array KStmt := #[]
  /-- Proof metadata recorded while emitting statements. -/
  proof : KernelProof := default
  /-- Target GPU architecture -/
  arch : GpuArch := .SM90
  /-- Shared memory usage tracking -/
  sharedMemBytes : Nat := 0
  deriving Inhabited, Repr

/-- Kernel builder monad - just standard StateM! -/
abbrev KernelM := StateM KernelState

/-- Generate a fresh variable ID -/
def freshVar : KernelM VarId := do
  let s ← get
  let v : VarId := ⟨s.nextId⟩
  set { s with nextId := s.nextId + 1 }
  pure v

/-- Emit a statement to the kernel body -/
def emit (stmt : KStmt) : KernelM Unit := do
  modify fun s => { s with body := s.body.push stmt }

/-- Update proof metadata without changing emitted IR. -/
def modifyProof (f : KernelProof → KernelProof) : KernelM Unit := do
  modify fun s => { s with proof := f s.proof }

/-- Record a structured scalar expression for a materialized runtime scalar. -/
def recordScalar (v : VarId) (expr : ScalarExpr) : KernelM Unit := do
  modifyProof fun p => p.insertScalar v expr

/-- Record a structured predicate for a materialized runtime boolean. -/
def recordPredicate (v : VarId) (pred : ThreadPred) : KernelM Unit := do
  modifyProof fun p => p.insertPredicate v pred

/-- Queue a proof obligation generated by a checked or proof-aware API. -/
def addProofObligation (obl : ProofObligation) : KernelM Unit := do
  modifyProof fun p => p.addObligation obl

/-- Queue an obligation only when the caller provides its Lean semantic proof. -/
def addCheckedObligation (ctx : ThreadCtx) (obl : ProofObligation)
    (proof : obl.kind.Holds ctx) : KernelM (ValidatedObligation ctx) := do
  addProofObligation obl
  pure (obl.certify ctx proof)

/-- Queue a proof-backed optimization decision and its certification obligation. -/
def addOptimizationProof {ctx : ThreadCtx} (cert : CertifiedOptimization ctx) : KernelM Unit := do
  modifyProof fun p => p.addCertifiedOptimization cert

/-- Queue a ShapeSync obligation generated by a proof-aware backend API. -/
def addShapeSyncObligation (obl : Tyr.ShapeSync.Obligation) : KernelM Unit := do
  modifyProof fun p => p.addShapeSyncObligation obl

/-- Record a producer/consumer analysis derived from a structured pipeline preview. -/
def addShapeSyncPipelineAnalysis
    (analysis : Tyr.ShapeSync.ProducerConsumerAnalysis) : KernelM Unit := do
  modifyProof fun p => p.addShapeSyncPipelineAnalysis analysis

/-- Current structured execution guard. -/
def currentProofGuard : KernelM ThreadPred := do
  pure (← get).proof.currentGuard

/-- Execute a builder action under an additional structured guard. -/
def withProofGuard (guard : ThreadPred) (action : KernelM α) : KernelM α := do
  modifyProof fun p => p.pushGuard guard
  let result ← action
  modifyProof fun p => p.popGuard
  pure result

/-- Add a comment to the kernel -/
def comment (text : String) : KernelM Unit := do
  emit (.comment text)

/-- Set the target architecture -/
def setArch (arch : GpuArch) : KernelM Unit := do
  modify fun s => { s with arch := arch }

/-- Build a Kernel from the accumulated state -/
def buildKernel (name : String) (params : Array KParam := #[]) : KernelM Kernel := do
  let s ← get
  let proof := s.proof.completeFromStmts s.body
  pure {
    name := name
    arch := s.arch
    params := params
    body := s.body
    sharedMemBytes := s.sharedMemBytes
    proof := proof
  }

/-- Run the kernel builder and extract the result -/
def runKernelM (arch : GpuArch := .SM90) (m : KernelM α) : α × KernelState :=
  m.run { arch := arch }

/-- Run and extract just the kernel.
    Note: nextId starts at params.size to avoid conflicts with parameter VarIds -/
def buildKernelM (name : String) (arch : GpuArch := .SM90)
    (params : Array KParam := #[]) (m : KernelM Unit) : Kernel :=
  -- Start nextId at params.size so freshVar doesn't conflict with parameter VarIds
  let (_, state) := m.run { arch := arch, nextId := params.size }
  {
    name := name
    arch := state.arch
    params := params
    body := state.body
    sharedMemBytes := state.sharedMemBytes
    proof := state.proof.completeFromStmts state.body
  }

/-- Capture loop body: saves state, runs body, extracts statements, restores -/
def captureBody (body : KernelM Unit) : KernelM (Array KStmt) := do
  let savedBody := (← get).body
  modify fun s => { s with body := #[] }
  body
  let capturedBody := (← get).body
  modify fun s => { s with body := savedBody }
  pure capturedBody

/-- Capture a body for analysis and restore the entire builder state afterward. -/
def captureBodySnapshot (body : KernelM Unit) : KernelM (Array KStmt) := do
  let saved ← get
  set { saved with body := #[] }
  body
  let capturedBody := (← get).body
  set saved
  pure capturedBody

end Tyr.GPU.Codegen
