-- Generated by capnpc-lean4; DO NOT EDIT.
-- source: model_gateway.capnp

import Capnp.Runtime
import Capnp.Rpc

set_option maxHeartbeats 2000000


namespace TyrModelServer.Capnp.model_gateway

structure ChatMessage.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ChatMessage.read (ptr : Capnp.AnyPointer) : ChatMessage.Reader := { struct := Capnp.readStruct ptr }
def ChatMessage.readChecked (ptr : Capnp.AnyPointer) : Except String ChatMessage.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ChatMessage.fromStruct (sr : Capnp.StructReader) : ChatMessage.Reader := { struct := sr }

structure ChatMessage.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ChatMessage.Builder.fromStruct (sb : Capnp.StructBuilder) : ChatMessage.Builder := { struct := sb }


structure ModelGateway.info_Params.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.info_Params.read (ptr : Capnp.AnyPointer) : ModelGateway.info_Params.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.info_Params.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.info_Params.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.info_Params.fromStruct (sr : Capnp.StructReader) : ModelGateway.info_Params.Reader := { struct := sr }

structure ModelGateway.info_Params.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.info_Params.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.info_Params.Builder := { struct := sb }


structure ModelGateway.info_Results.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.info_Results.read (ptr : Capnp.AnyPointer) : ModelGateway.info_Results.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.info_Results.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.info_Results.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.info_Results.fromStruct (sr : Capnp.StructReader) : ModelGateway.info_Results.Reader := { struct := sr }

structure ModelGateway.info_Results.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.info_Results.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.info_Results.Builder := { struct := sb }


structure ModelGateway.generate_Params.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.generate_Params.read (ptr : Capnp.AnyPointer) : ModelGateway.generate_Params.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.generate_Params.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.generate_Params.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.generate_Params.fromStruct (sr : Capnp.StructReader) : ModelGateway.generate_Params.Reader := { struct := sr }

structure ModelGateway.generate_Params.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.generate_Params.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.generate_Params.Builder := { struct := sb }


structure ModelGateway.generate_Results.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.generate_Results.read (ptr : Capnp.AnyPointer) : ModelGateway.generate_Results.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.generate_Results.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.generate_Results.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.generate_Results.fromStruct (sr : Capnp.StructReader) : ModelGateway.generate_Results.Reader := { struct := sr }

structure ModelGateway.generate_Results.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.generate_Results.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.generate_Results.Builder := { struct := sb }


structure ModelGateway.tokenize_Params.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.tokenize_Params.read (ptr : Capnp.AnyPointer) : ModelGateway.tokenize_Params.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.tokenize_Params.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.tokenize_Params.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.tokenize_Params.fromStruct (sr : Capnp.StructReader) : ModelGateway.tokenize_Params.Reader := { struct := sr }

structure ModelGateway.tokenize_Params.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.tokenize_Params.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.tokenize_Params.Builder := { struct := sb }


structure ModelGateway.tokenize_Results.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.tokenize_Results.read (ptr : Capnp.AnyPointer) : ModelGateway.tokenize_Results.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.tokenize_Results.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.tokenize_Results.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.tokenize_Results.fromStruct (sr : Capnp.StructReader) : ModelGateway.tokenize_Results.Reader := { struct := sr }

structure ModelGateway.tokenize_Results.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.tokenize_Results.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.tokenize_Results.Builder := { struct := sb }


structure ModelGateway.decode_Params.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.decode_Params.read (ptr : Capnp.AnyPointer) : ModelGateway.decode_Params.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.decode_Params.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.decode_Params.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.decode_Params.fromStruct (sr : Capnp.StructReader) : ModelGateway.decode_Params.Reader := { struct := sr }

structure ModelGateway.decode_Params.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.decode_Params.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.decode_Params.Builder := { struct := sb }


structure ModelGateway.decode_Results.Reader where
  struct : Capnp.StructReader

  deriving BEq

def ModelGateway.decode_Results.read (ptr : Capnp.AnyPointer) : ModelGateway.decode_Results.Reader := { struct := Capnp.readStruct ptr }
def ModelGateway.decode_Results.readChecked (ptr : Capnp.AnyPointer) : Except String ModelGateway.decode_Results.Reader := do
  let sr ← Capnp.readStructChecked ptr
  return { struct := sr }
def ModelGateway.decode_Results.fromStruct (sr : Capnp.StructReader) : ModelGateway.decode_Results.Reader := { struct := sr }

structure ModelGateway.decode_Results.Builder where
  struct : Capnp.StructBuilder

  deriving BEq

def ModelGateway.decode_Results.Builder.fromStruct (sb : Capnp.StructBuilder) : ModelGateway.decode_Results.Builder := { struct := sb }


abbrev ModelGateway := Capnp.Rpc.Client

namespace ModelGateway

def interfaceId : UInt64 := UInt64.ofNat 13556355690471399334

def infoMethodId : UInt16 := UInt16.ofNat 0
def infoMethod : Capnp.Rpc.Method := { interfaceId := interfaceId, methodId := infoMethodId }
def callInfo (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.Payload := do
  Capnp.Rpc.call backend target infoMethod payload
def callInfoM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  Capnp.Rpc.RuntimeM.call target infoMethod payload
def callInfoWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.Runtime.callWithPayloadRef runtime target infoMethod payloadRef
def callInfoWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.RuntimeM.callWithPayloadRef target infoMethod payloadRef
def startInfo (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCall runtime target infoMethod payload
def startInfoM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCall target infoMethod payload
def startInfoWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCallWithPayloadRef runtime target infoMethod payloadRef
def startInfoWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCallWithPayloadRef target infoMethod payloadRef
def awaitInfo (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.Payload := do
  pendingCall.await
def awaitInfoPayloadRef (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  pendingCall.awaitPayloadRef
abbrev InfoResponse := Capnp.Rpc.TypedPayload TyrModelServer.Capnp.model_gateway.ModelGateway.info_Results.Reader
abbrev InfoPromise := Capnp.Rpc.Promise InfoResponse
def startInfoPromise (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO InfoPromise := do
  return { pendingCall := (← startInfo runtime target payload) }
def startInfoPromiseM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM InfoPromise := do
  return { pendingCall := (← startInfoM target payload) }
def InfoPromise.await (promise : InfoPromise) : IO Capnp.Rpc.Payload := do
  awaitInfo promise.pendingCall
def InfoPromise.awaitPayloadRef (promise : InfoPromise) : IO Capnp.Rpc.RuntimePayloadRef := do
  awaitInfoPayloadRef promise.pendingCall
def InfoPromise.release (promise : InfoPromise) : IO Unit :=
  promise.pendingCall.release
def InfoPromise.releaseDeferred (promise : InfoPromise) : IO Unit :=
  promise.pendingCall.releaseDeferred
abbrev infoTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.info_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.Payload
abbrev infoAdvancedTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.info_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
abbrev infoStreamingTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.info_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
def infoRequestOfPayload (payload : Capnp.Rpc.Payload) : IO (TyrModelServer.Capnp.model_gateway.ModelGateway.info_Params.Reader × Capnp.CapTable) := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.info_Params.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid infoMethod request: {e}")
  return (reader, payload.capTable)
def infoResponseOfPayload (payload : Capnp.Rpc.Payload) : IO InfoResponse := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.info_Results.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid infoMethod response: {e}")
  return { reader := reader, capTable := payload.capTable }
def callInfoTyped (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO InfoResponse := do
  let response ← Capnp.Rpc.call backend target infoMethod payload
  infoResponseOfPayload response
def callInfoTypedM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM InfoResponse := do
  let response ← Capnp.Rpc.RuntimeM.call target infoMethod payload
  infoResponseOfPayload response
def awaitInfoTyped (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO InfoResponse := do
  let response ← pendingCall.await
  infoResponseOfPayload response
def InfoPromise.awaitTyped (promise : InfoPromise) : IO InfoResponse := do
  awaitInfoTyped promise.pendingCall
def getInfoPipelinedCap (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  pendingCall.getPipelinedCap pointerPath
def callInfoPipelinedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  let target ← Capnp.Rpc.RuntimeM.pendingCallGetPipelinedCap pendingCall pointerPath
  Capnp.Rpc.RuntimeM.call target infoMethod payload
def callInfoPipelinedTypedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM InfoResponse := do
  let response ← callInfoPipelinedM pendingCall pointerPath payload
  infoResponseOfPayload response
def InfoPromise.getPipelinedCap (promise : InfoPromise)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  getInfoPipelinedCap promise.pendingCall pointerPath
def InfoPromise.callPipelinedM (promise : InfoPromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  callInfoPipelinedM promise.pendingCall pointerPath payload
def InfoPromise.callPipelinedTypedM (promise : InfoPromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM InfoResponse := do
  callInfoPipelinedTypedM promise.pendingCall pointerPath payload

def generateMethodId : UInt16 := UInt16.ofNat 1
def generateMethod : Capnp.Rpc.Method := { interfaceId := interfaceId, methodId := generateMethodId }
def callGenerate (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.Payload := do
  Capnp.Rpc.call backend target generateMethod payload
def callGenerateM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  Capnp.Rpc.RuntimeM.call target generateMethod payload
def callGenerateWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.Runtime.callWithPayloadRef runtime target generateMethod payloadRef
def callGenerateWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.RuntimeM.callWithPayloadRef target generateMethod payloadRef
def startGenerate (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCall runtime target generateMethod payload
def startGenerateM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCall target generateMethod payload
def startGenerateWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCallWithPayloadRef runtime target generateMethod payloadRef
def startGenerateWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCallWithPayloadRef target generateMethod payloadRef
def awaitGenerate (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.Payload := do
  pendingCall.await
def awaitGeneratePayloadRef (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  pendingCall.awaitPayloadRef
abbrev GenerateResponse := Capnp.Rpc.TypedPayload TyrModelServer.Capnp.model_gateway.ModelGateway.generate_Results.Reader
abbrev GeneratePromise := Capnp.Rpc.Promise GenerateResponse
def startGeneratePromise (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO GeneratePromise := do
  return { pendingCall := (← startGenerate runtime target payload) }
def startGeneratePromiseM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM GeneratePromise := do
  return { pendingCall := (← startGenerateM target payload) }
def GeneratePromise.await (promise : GeneratePromise) : IO Capnp.Rpc.Payload := do
  awaitGenerate promise.pendingCall
def GeneratePromise.awaitPayloadRef (promise : GeneratePromise) : IO Capnp.Rpc.RuntimePayloadRef := do
  awaitGeneratePayloadRef promise.pendingCall
def GeneratePromise.release (promise : GeneratePromise) : IO Unit :=
  promise.pendingCall.release
def GeneratePromise.releaseDeferred (promise : GeneratePromise) : IO Unit :=
  promise.pendingCall.releaseDeferred
abbrev generateTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.generate_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.Payload
abbrev generateAdvancedTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.generate_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
abbrev generateStreamingTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.generate_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
def generateRequestOfPayload (payload : Capnp.Rpc.Payload) : IO (TyrModelServer.Capnp.model_gateway.ModelGateway.generate_Params.Reader × Capnp.CapTable) := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.generate_Params.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid generateMethod request: {e}")
  return (reader, payload.capTable)
def generateResponseOfPayload (payload : Capnp.Rpc.Payload) : IO GenerateResponse := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.generate_Results.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid generateMethod response: {e}")
  return { reader := reader, capTable := payload.capTable }
def callGenerateTyped (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO GenerateResponse := do
  let response ← Capnp.Rpc.call backend target generateMethod payload
  generateResponseOfPayload response
def callGenerateTypedM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM GenerateResponse := do
  let response ← Capnp.Rpc.RuntimeM.call target generateMethod payload
  generateResponseOfPayload response
def awaitGenerateTyped (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO GenerateResponse := do
  let response ← pendingCall.await
  generateResponseOfPayload response
def GeneratePromise.awaitTyped (promise : GeneratePromise) : IO GenerateResponse := do
  awaitGenerateTyped promise.pendingCall
def getGeneratePipelinedCap (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  pendingCall.getPipelinedCap pointerPath
def callGeneratePipelinedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  let target ← Capnp.Rpc.RuntimeM.pendingCallGetPipelinedCap pendingCall pointerPath
  Capnp.Rpc.RuntimeM.call target generateMethod payload
def callGeneratePipelinedTypedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM GenerateResponse := do
  let response ← callGeneratePipelinedM pendingCall pointerPath payload
  generateResponseOfPayload response
def GeneratePromise.getPipelinedCap (promise : GeneratePromise)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  getGeneratePipelinedCap promise.pendingCall pointerPath
def GeneratePromise.callPipelinedM (promise : GeneratePromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  callGeneratePipelinedM promise.pendingCall pointerPath payload
def GeneratePromise.callPipelinedTypedM (promise : GeneratePromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM GenerateResponse := do
  callGeneratePipelinedTypedM promise.pendingCall pointerPath payload

def tokenizeMethodId : UInt16 := UInt16.ofNat 2
def tokenizeMethod : Capnp.Rpc.Method := { interfaceId := interfaceId, methodId := tokenizeMethodId }
def callTokenize (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.Payload := do
  Capnp.Rpc.call backend target tokenizeMethod payload
def callTokenizeM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  Capnp.Rpc.RuntimeM.call target tokenizeMethod payload
def callTokenizeWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.Runtime.callWithPayloadRef runtime target tokenizeMethod payloadRef
def callTokenizeWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.RuntimeM.callWithPayloadRef target tokenizeMethod payloadRef
def startTokenize (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCall runtime target tokenizeMethod payload
def startTokenizeM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCall target tokenizeMethod payload
def startTokenizeWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCallWithPayloadRef runtime target tokenizeMethod payloadRef
def startTokenizeWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCallWithPayloadRef target tokenizeMethod payloadRef
def awaitTokenize (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.Payload := do
  pendingCall.await
def awaitTokenizePayloadRef (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  pendingCall.awaitPayloadRef
abbrev TokenizeResponse := Capnp.Rpc.TypedPayload TyrModelServer.Capnp.model_gateway.ModelGateway.tokenize_Results.Reader
abbrev TokenizePromise := Capnp.Rpc.Promise TokenizeResponse
def startTokenizePromise (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO TokenizePromise := do
  return { pendingCall := (← startTokenize runtime target payload) }
def startTokenizePromiseM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM TokenizePromise := do
  return { pendingCall := (← startTokenizeM target payload) }
def TokenizePromise.await (promise : TokenizePromise) : IO Capnp.Rpc.Payload := do
  awaitTokenize promise.pendingCall
def TokenizePromise.awaitPayloadRef (promise : TokenizePromise) : IO Capnp.Rpc.RuntimePayloadRef := do
  awaitTokenizePayloadRef promise.pendingCall
def TokenizePromise.release (promise : TokenizePromise) : IO Unit :=
  promise.pendingCall.release
def TokenizePromise.releaseDeferred (promise : TokenizePromise) : IO Unit :=
  promise.pendingCall.releaseDeferred
abbrev tokenizeTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.tokenize_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.Payload
abbrev tokenizeAdvancedTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.tokenize_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
abbrev tokenizeStreamingTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.tokenize_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
def tokenizeRequestOfPayload (payload : Capnp.Rpc.Payload) : IO (TyrModelServer.Capnp.model_gateway.ModelGateway.tokenize_Params.Reader × Capnp.CapTable) := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.tokenize_Params.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid tokenizeMethod request: {e}")
  return (reader, payload.capTable)
def tokenizeResponseOfPayload (payload : Capnp.Rpc.Payload) : IO TokenizeResponse := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.tokenize_Results.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid tokenizeMethod response: {e}")
  return { reader := reader, capTable := payload.capTable }
def callTokenizeTyped (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO TokenizeResponse := do
  let response ← Capnp.Rpc.call backend target tokenizeMethod payload
  tokenizeResponseOfPayload response
def callTokenizeTypedM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM TokenizeResponse := do
  let response ← Capnp.Rpc.RuntimeM.call target tokenizeMethod payload
  tokenizeResponseOfPayload response
def awaitTokenizeTyped (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO TokenizeResponse := do
  let response ← pendingCall.await
  tokenizeResponseOfPayload response
def TokenizePromise.awaitTyped (promise : TokenizePromise) : IO TokenizeResponse := do
  awaitTokenizeTyped promise.pendingCall
def getTokenizePipelinedCap (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  pendingCall.getPipelinedCap pointerPath
def callTokenizePipelinedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  let target ← Capnp.Rpc.RuntimeM.pendingCallGetPipelinedCap pendingCall pointerPath
  Capnp.Rpc.RuntimeM.call target tokenizeMethod payload
def callTokenizePipelinedTypedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM TokenizeResponse := do
  let response ← callTokenizePipelinedM pendingCall pointerPath payload
  tokenizeResponseOfPayload response
def TokenizePromise.getPipelinedCap (promise : TokenizePromise)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  getTokenizePipelinedCap promise.pendingCall pointerPath
def TokenizePromise.callPipelinedM (promise : TokenizePromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  callTokenizePipelinedM promise.pendingCall pointerPath payload
def TokenizePromise.callPipelinedTypedM (promise : TokenizePromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM TokenizeResponse := do
  callTokenizePipelinedTypedM promise.pendingCall pointerPath payload

def decodeMethodId : UInt16 := UInt16.ofNat 3
def decodeMethod : Capnp.Rpc.Method := { interfaceId := interfaceId, methodId := decodeMethodId }
def callDecode (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.Payload := do
  Capnp.Rpc.call backend target decodeMethod payload
def callDecodeM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  Capnp.Rpc.RuntimeM.call target decodeMethod payload
def callDecodeWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.Runtime.callWithPayloadRef runtime target decodeMethod payloadRef
def callDecodeWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePayloadRef := do
  Capnp.Rpc.RuntimeM.callWithPayloadRef target decodeMethod payloadRef
def startDecode (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCall runtime target decodeMethod payload
def startDecodeM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCall target decodeMethod payload
def startDecodeWithPayloadRef (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : IO Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.Runtime.startCallWithPayloadRef runtime target decodeMethod payloadRef
def startDecodeWithPayloadRefM (target : ModelGateway) (payloadRef : Capnp.Rpc.RuntimePayloadRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimePendingCallRef := do
  Capnp.Rpc.RuntimeM.startCallWithPayloadRef target decodeMethod payloadRef
def awaitDecode (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.Payload := do
  pendingCall.await
def awaitDecodePayloadRef (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO Capnp.Rpc.RuntimePayloadRef := do
  pendingCall.awaitPayloadRef
abbrev DecodeResponse := Capnp.Rpc.TypedPayload TyrModelServer.Capnp.model_gateway.ModelGateway.decode_Results.Reader
abbrev DecodePromise := Capnp.Rpc.Promise DecodeResponse
def startDecodePromise (runtime : Capnp.Rpc.Runtime) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO DecodePromise := do
  return { pendingCall := (← startDecode runtime target payload) }
def startDecodePromiseM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM DecodePromise := do
  return { pendingCall := (← startDecodeM target payload) }
def DecodePromise.await (promise : DecodePromise) : IO Capnp.Rpc.Payload := do
  awaitDecode promise.pendingCall
def DecodePromise.awaitPayloadRef (promise : DecodePromise) : IO Capnp.Rpc.RuntimePayloadRef := do
  awaitDecodePayloadRef promise.pendingCall
def DecodePromise.release (promise : DecodePromise) : IO Unit :=
  promise.pendingCall.release
def DecodePromise.releaseDeferred (promise : DecodePromise) : IO Unit :=
  promise.pendingCall.releaseDeferred
abbrev decodeTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.decode_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.Payload
abbrev decodeAdvancedTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.decode_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
abbrev decodeStreamingTypedHandler := Capnp.Rpc.Client -> TyrModelServer.Capnp.model_gateway.ModelGateway.decode_Params.Reader -> Capnp.CapTable -> IO Capnp.Rpc.AdvancedHandlerReply
def decodeRequestOfPayload (payload : Capnp.Rpc.Payload) : IO (TyrModelServer.Capnp.model_gateway.ModelGateway.decode_Params.Reader × Capnp.CapTable) := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.decode_Params.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid decodeMethod request: {e}")
  return (reader, payload.capTable)
def decodeResponseOfPayload (payload : Capnp.Rpc.Payload) : IO DecodeResponse := do
  let reader ← match TyrModelServer.Capnp.model_gateway.ModelGateway.decode_Results.readChecked (Capnp.getRoot payload.msg) with
    | Except.ok r => pure r
    | Except.error e => throw (IO.userError s!"invalid decodeMethod response: {e}")
  return { reader := reader, capTable := payload.capTable }
def callDecodeTyped (backend : Capnp.Rpc.Backend) (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : IO DecodeResponse := do
  let response ← Capnp.Rpc.call backend target decodeMethod payload
  decodeResponseOfPayload response
def callDecodeTypedM (target : ModelGateway) (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM DecodeResponse := do
  let response ← Capnp.Rpc.RuntimeM.call target decodeMethod payload
  decodeResponseOfPayload response
def awaitDecodeTyped (pendingCall : Capnp.Rpc.RuntimePendingCallRef) : IO DecodeResponse := do
  let response ← pendingCall.await
  decodeResponseOfPayload response
def DecodePromise.awaitTyped (promise : DecodePromise) : IO DecodeResponse := do
  awaitDecodeTyped promise.pendingCall
def getDecodePipelinedCap (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  pendingCall.getPipelinedCap pointerPath
def callDecodePipelinedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  let target ← Capnp.Rpc.RuntimeM.pendingCallGetPipelinedCap pendingCall pointerPath
  Capnp.Rpc.RuntimeM.call target decodeMethod payload
def callDecodePipelinedTypedM (pendingCall : Capnp.Rpc.RuntimePendingCallRef)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM DecodeResponse := do
  let response ← callDecodePipelinedM pendingCall pointerPath payload
  decodeResponseOfPayload response
def DecodePromise.getPipelinedCap (promise : DecodePromise)
    (pointerPath : Array UInt16 := #[]) : IO ModelGateway := do
  getDecodePipelinedCap promise.pendingCall pointerPath
def DecodePromise.callPipelinedM (promise : DecodePromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM Capnp.Rpc.Payload := do
  callDecodePipelinedM promise.pendingCall pointerPath payload
def DecodePromise.callPipelinedTypedM (promise : DecodePromise)
    (pointerPath : Array UInt16 := #[])
    (payload : Capnp.Rpc.Payload := Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM DecodeResponse := do
  callDecodePipelinedTypedM promise.pendingCall pointerPath payload

def restoreSturdyRef (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : IO ModelGateway := do
  peer.restoreSturdyRef sturdyRef
def restoreSturdyRefM (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : Capnp.Rpc.RuntimeM ModelGateway := do
  Capnp.Rpc.RuntimeM.multiVatRestoreSturdyRef peer sturdyRef
def restoreSturdyRefStart (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : IO Capnp.Rpc.RuntimeRegisterPromiseRef := do
  peer.restoreSturdyRefStart sturdyRef
def restoreSturdyRefStartM (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : Capnp.Rpc.RuntimeM Capnp.Rpc.RuntimeRegisterPromiseRef := do
  Capnp.Rpc.RuntimeM.multiVatRestoreSturdyRefStart peer sturdyRef
def awaitRestoreSturdyRef (promise : Capnp.Rpc.RuntimeRegisterPromiseRef) : IO ModelGateway := do
  promise.awaitTarget
def restoreSturdyRefAsTask (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : IO (Task (Except IO.Error ModelGateway)) := do
  peer.restoreSturdyRefAsTask sturdyRef
def restoreSturdyRefAsTaskM (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : Capnp.Rpc.RuntimeM (Task (Except IO.Error ModelGateway)) := do
  Capnp.Rpc.RuntimeM.multiVatRestoreSturdyRefAsTask peer sturdyRef
def restoreSturdyRefAsPromise (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : IO (Capnp.Async.Promise ModelGateway) := do
  peer.restoreSturdyRefAsPromise sturdyRef
def restoreSturdyRefAsPromiseM (peer : Capnp.Rpc.RuntimeVatPeerRef) (sturdyRef : Capnp.Rpc.SturdyRef) : Capnp.Rpc.RuntimeM (Capnp.Async.Promise ModelGateway) := do
  Capnp.Rpc.RuntimeM.multiVatRestoreSturdyRefAsPromise peer sturdyRef

def newPromiseCapability (runtime : Capnp.Rpc.Runtime) : IO (ModelGateway × Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef) := do
  runtime.newPromiseCapability
def newPromiseCapabilityM : Capnp.Rpc.RuntimeM (ModelGateway × Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef) := do
  Capnp.Rpc.RuntimeM.newPromiseCapability
def promiseCapabilityFulfill (fulfiller : Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef) (target : ModelGateway) : IO Unit := do
  fulfiller.fulfill target
def promiseCapabilityFulfillM (fulfiller : Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef) (target : ModelGateway) : Capnp.Rpc.RuntimeM Unit := do
  Capnp.Rpc.RuntimeM.promiseCapabilityFulfill fulfiller target
def promiseCapabilityReject (fulfiller : Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef)
    (type : Capnp.Rpc.RemoteExceptionType)
    (message : String := "")
    (detail : ByteArray := ByteArray.empty) : IO Unit := do
  fulfiller.reject type message detail
def promiseCapabilityRejectM (fulfiller : Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef)
    (type : Capnp.Rpc.RemoteExceptionType)
    (message : String := "")
    (detail : ByteArray := ByteArray.empty) : Capnp.Rpc.RuntimeM Unit := do
  Capnp.Rpc.RuntimeM.promiseCapabilityReject fulfiller type message detail
def promiseCapabilityRelease (fulfiller : Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef) : IO Unit := do
  fulfiller.release
def promiseCapabilityReleaseM (fulfiller : Capnp.Rpc.RuntimePromiseCapabilityFulfillerRef) : Capnp.Rpc.RuntimeM Unit := do
  Capnp.Rpc.RuntimeM.promiseCapabilityRelease fulfiller

abbrev Handler := Capnp.Rpc.Handler
abbrev infoHandler := Handler
abbrev generateHandler := Handler
abbrev tokenizeHandler := Handler
abbrev decodeHandler := Handler

structure Server where
  info : infoHandler
  generate : generateHandler
  tokenize : tokenizeHandler
  decode : decodeHandler

def dispatch (server : Server) : Capnp.Rpc.Dispatch := Id.run do
  let mut d := Capnp.Rpc.Dispatch.empty
  d := Capnp.Rpc.Dispatch.register d infoMethod server.info
  d := Capnp.Rpc.Dispatch.register d generateMethod server.generate
  d := Capnp.Rpc.Dispatch.register d tokenizeMethod server.tokenize
  d := Capnp.Rpc.Dispatch.register d decodeMethod server.decode
  return d

def backend (server : Server)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.Payload := fun _ _ _ => pure Capnp.emptyRpcEnvelope) : Capnp.Rpc.Backend where
  call := fun target method payload => do
    if method == infoMethod then
      server.info target payload
    else if method == generateMethod then
      server.generate target payload
    else if method == tokenizeMethod then
      server.tokenize target payload
    else if method == decodeMethod then
      server.decode target payload
    else
      onMissing target method payload

def registerTarget (runtime : Capnp.Rpc.Runtime) (server : Server)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.Payload := fun _ _ _ => pure Capnp.emptyRpcEnvelope) : IO ModelGateway := do
  Capnp.Rpc.Runtime.registerBackendTarget runtime (backend server (onMissing := onMissing))

def registerTargetM (server : Server)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.Payload := fun _ _ _ => pure Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM ModelGateway := do
  Capnp.Rpc.RuntimeM.registerBackendTarget (backend server (onMissing := onMissing))

structure TypedServer where
  info : infoTypedHandler
  generate : generateTypedHandler
  tokenize : tokenizeTypedHandler
  decode : decodeTypedHandler

def typedDispatch (server : TypedServer) : Capnp.Rpc.Dispatch := Id.run do
  let mut d := Capnp.Rpc.Dispatch.empty
  d := Capnp.Rpc.Dispatch.register d infoMethod (fun target payload => do
    let (request, requestCaps) ← infoRequestOfPayload payload
    server.info target request requestCaps
  )
  d := Capnp.Rpc.Dispatch.register d generateMethod (fun target payload => do
    let (request, requestCaps) ← generateRequestOfPayload payload
    server.generate target request requestCaps
  )
  d := Capnp.Rpc.Dispatch.register d tokenizeMethod (fun target payload => do
    let (request, requestCaps) ← tokenizeRequestOfPayload payload
    server.tokenize target request requestCaps
  )
  d := Capnp.Rpc.Dispatch.register d decodeMethod (fun target payload => do
    let (request, requestCaps) ← decodeRequestOfPayload payload
    server.decode target request requestCaps
  )
  return d

def typedBackend (server : TypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.Payload := fun _ _ _ => pure Capnp.emptyRpcEnvelope) : Capnp.Rpc.Backend where
  call := fun target method payload => do
    if method == infoMethod then do
      let (request, requestCaps) ← infoRequestOfPayload payload
      server.info target request requestCaps
    else if method == generateMethod then do
      let (request, requestCaps) ← generateRequestOfPayload payload
      server.generate target request requestCaps
    else if method == tokenizeMethod then do
      let (request, requestCaps) ← tokenizeRequestOfPayload payload
      server.tokenize target request requestCaps
    else if method == decodeMethod then do
      let (request, requestCaps) ← decodeRequestOfPayload payload
      server.decode target request requestCaps
    else
      onMissing target method payload

def registerTypedTarget (runtime : Capnp.Rpc.Runtime) (server : TypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.Payload := fun _ _ _ => pure Capnp.emptyRpcEnvelope) : IO ModelGateway := do
  Capnp.Rpc.Runtime.registerBackendTarget runtime (typedBackend server (onMissing := onMissing))

def registerTypedTargetM (server : TypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.Payload := fun _ _ _ => pure Capnp.emptyRpcEnvelope) : Capnp.Rpc.RuntimeM ModelGateway := do
  Capnp.Rpc.RuntimeM.registerBackendTarget (typedBackend server (onMissing := onMissing))

structure AdvancedTypedServer where
  info : infoAdvancedTypedHandler
  generate : generateAdvancedTypedHandler
  tokenize : tokenizeAdvancedTypedHandler
  decode : decodeAdvancedTypedHandler

def advancedTypedTargetHandler (server : AdvancedTypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply := fun _ _ _ => pure (Capnp.Rpc.Advanced.now (Capnp.Rpc.Advanced.respond Capnp.emptyRpcEnvelope))) : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply :=
  fun target method payload => do
    if method == infoMethod then do
      let (request, requestCaps) ← infoRequestOfPayload payload
      server.info target request requestCaps
    else if method == generateMethod then do
      let (request, requestCaps) ← generateRequestOfPayload payload
      server.generate target request requestCaps
    else if method == tokenizeMethod then do
      let (request, requestCaps) ← tokenizeRequestOfPayload payload
      server.tokenize target request requestCaps
    else if method == decodeMethod then do
      let (request, requestCaps) ← decodeRequestOfPayload payload
      server.decode target request requestCaps
    else
      onMissing target method payload

def registerAdvancedTypedTarget (runtime : Capnp.Rpc.Runtime) (server : AdvancedTypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply := fun _ _ _ => pure (Capnp.Rpc.Advanced.now (Capnp.Rpc.Advanced.respond Capnp.emptyRpcEnvelope))) : IO ModelGateway := do
  Capnp.Rpc.Runtime.registerAdvancedHandlerTargetAsync runtime (advancedTypedTargetHandler server (onMissing := onMissing))

def registerAdvancedTypedTargetM (server : AdvancedTypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply := fun _ _ _ => pure (Capnp.Rpc.Advanced.now (Capnp.Rpc.Advanced.respond Capnp.emptyRpcEnvelope))) : Capnp.Rpc.RuntimeM ModelGateway := do
  Capnp.Rpc.RuntimeM.registerAdvancedHandlerTargetAsync (advancedTypedTargetHandler server (onMissing := onMissing))

structure StreamingTypedServer where
  info : infoStreamingTypedHandler
  generate : generateStreamingTypedHandler
  tokenize : tokenizeStreamingTypedHandler
  decode : decodeStreamingTypedHandler

def streamingTypedTargetHandler (server : StreamingTypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply := fun _ _ _ => pure (Capnp.Rpc.Advanced.now (Capnp.Rpc.Advanced.respond Capnp.emptyRpcEnvelope))) : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply :=
  fun target method payload => do
    if method == infoMethod then do
      let (request, requestCaps) ← infoRequestOfPayload payload
      server.info target request requestCaps
    else if method == generateMethod then do
      let (request, requestCaps) ← generateRequestOfPayload payload
      server.generate target request requestCaps
    else if method == tokenizeMethod then do
      let (request, requestCaps) ← tokenizeRequestOfPayload payload
      server.tokenize target request requestCaps
    else if method == decodeMethod then do
      let (request, requestCaps) ← decodeRequestOfPayload payload
      server.decode target request requestCaps
    else
      onMissing target method payload

def registerStreamingTypedTarget (runtime : Capnp.Rpc.Runtime) (server : StreamingTypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply := fun _ _ _ => pure (Capnp.Rpc.Advanced.now (Capnp.Rpc.Advanced.respond Capnp.emptyRpcEnvelope))) : IO ModelGateway := do
  Capnp.Rpc.Runtime.registerStreamingHandlerTargetAsync runtime (streamingTypedTargetHandler server (onMissing := onMissing))

def registerStreamingTypedTargetM (server : StreamingTypedServer)
    (onMissing : Capnp.Rpc.Client -> Capnp.Rpc.Method -> Capnp.Rpc.Payload -> IO Capnp.Rpc.AdvancedHandlerReply := fun _ _ _ => pure (Capnp.Rpc.Advanced.now (Capnp.Rpc.Advanced.respond Capnp.emptyRpcEnvelope))) : Capnp.Rpc.RuntimeM ModelGateway := do
  Capnp.Rpc.RuntimeM.registerStreamingHandlerTargetAsync (streamingTypedTargetHandler server (onMissing := onMissing))

end ModelGateway

mutual
  structure ChatMessage where
    role : Capnp.Text
    content : Capnp.Text


  structure ModelGateway.info_Params where


  structure ModelGateway.info_Results where
    modelId : Capnp.Text
    source : Capnp.Text
    modelDir : Capnp.Text
    device : Capnp.Text
    maxContextTokens : UInt32
    vocabSize : UInt32
    supportsThinking : Bool
    supportsVision : Bool


  structure ModelGateway.generate_Params where
    messages : Array ChatMessage
    maxNewTokens : UInt32
    temperature : Float
    topK : UInt32
    topP : Float
    enableThinking : Bool


  structure ModelGateway.generate_Results where
    text : Capnp.Text
    generatedTokens : Array UInt32
    promptTokenCount : UInt32
    generatedTokenCount : UInt32
    stopReason : Capnp.Text


  structure ModelGateway.tokenize_Params where
    text : Capnp.Text


  structure ModelGateway.tokenize_Results where
    tokens : Array UInt32


  structure ModelGateway.decode_Params where
    tokens : Array UInt32


  structure ModelGateway.decode_Results where
    text : Capnp.Text


end


def ChatMessage.Reader.getRole (r : ChatMessage.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 0)
def ChatMessage.Reader.getRoleChecked (r : ChatMessage.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 0)
def ChatMessage.Reader.getRoleView (r : ChatMessage.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 0)
def ChatMessage.Reader.getRoleViewChecked (r : ChatMessage.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 0)

def ChatMessage.Reader.hasRole (r : ChatMessage.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)


def ChatMessage.Reader.getContent (r : ChatMessage.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 1)
def ChatMessage.Reader.getContentChecked (r : ChatMessage.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 1)
def ChatMessage.Reader.getContentView (r : ChatMessage.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 1)
def ChatMessage.Reader.getContentViewChecked (r : ChatMessage.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 1)

def ChatMessage.Reader.hasContent (r : ChatMessage.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 1)

def ChatMessage.initRoot : Capnp.BuilderM ChatMessage.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 0 2
  return { struct := sb }

def ChatMessage.Builder.clearRole (b : ChatMessage.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ChatMessage.Builder.setRole (b : ChatMessage.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 0) v

def ChatMessage.Builder.clearContent (b : ChatMessage.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 1)

def ChatMessage.Builder.setContent (b : ChatMessage.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 1) v

def ModelGateway.info_Params.initRoot : Capnp.BuilderM ModelGateway.info_Params.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 0 0
  return { struct := sb }


def ModelGateway.info_Results.Reader.getModelId (r : ModelGateway.info_Results.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 0)
def ModelGateway.info_Results.Reader.getModelIdChecked (r : ModelGateway.info_Results.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 0)
def ModelGateway.info_Results.Reader.getModelIdView (r : ModelGateway.info_Results.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 0)
def ModelGateway.info_Results.Reader.getModelIdViewChecked (r : ModelGateway.info_Results.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 0)

def ModelGateway.info_Results.Reader.hasModelId (r : ModelGateway.info_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)


def ModelGateway.info_Results.Reader.getSource (r : ModelGateway.info_Results.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 1)
def ModelGateway.info_Results.Reader.getSourceChecked (r : ModelGateway.info_Results.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 1)
def ModelGateway.info_Results.Reader.getSourceView (r : ModelGateway.info_Results.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 1)
def ModelGateway.info_Results.Reader.getSourceViewChecked (r : ModelGateway.info_Results.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 1)

def ModelGateway.info_Results.Reader.hasSource (r : ModelGateway.info_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 1)


def ModelGateway.info_Results.Reader.getModelDir (r : ModelGateway.info_Results.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 2)
def ModelGateway.info_Results.Reader.getModelDirChecked (r : ModelGateway.info_Results.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 2)
def ModelGateway.info_Results.Reader.getModelDirView (r : ModelGateway.info_Results.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 2)
def ModelGateway.info_Results.Reader.getModelDirViewChecked (r : ModelGateway.info_Results.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 2)

def ModelGateway.info_Results.Reader.hasModelDir (r : ModelGateway.info_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 2)


def ModelGateway.info_Results.Reader.getDevice (r : ModelGateway.info_Results.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 3)
def ModelGateway.info_Results.Reader.getDeviceChecked (r : ModelGateway.info_Results.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 3)
def ModelGateway.info_Results.Reader.getDeviceView (r : ModelGateway.info_Results.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 3)
def ModelGateway.info_Results.Reader.getDeviceViewChecked (r : ModelGateway.info_Results.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 3)

def ModelGateway.info_Results.Reader.hasDevice (r : ModelGateway.info_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 3)


def ModelGateway.info_Results.Reader.getMaxContextTokens (r : ModelGateway.info_Results.Reader) : UInt32 := Capnp.getUInt32 r.struct 0
def ModelGateway.info_Results.Reader.getMaxContextTokensChecked (r : ModelGateway.info_Results.Reader) : Except String (UInt32) := pure (Capnp.getUInt32 r.struct 0)

def ModelGateway.info_Results.Reader.getVocabSize (r : ModelGateway.info_Results.Reader) : UInt32 := Capnp.getUInt32 r.struct 4
def ModelGateway.info_Results.Reader.getVocabSizeChecked (r : ModelGateway.info_Results.Reader) : Except String (UInt32) := pure (Capnp.getUInt32 r.struct 4)

def ModelGateway.info_Results.Reader.getSupportsThinking (r : ModelGateway.info_Results.Reader) : Bool := Capnp.getBool r.struct 64
def ModelGateway.info_Results.Reader.getSupportsThinkingChecked (r : ModelGateway.info_Results.Reader) : Except String (Bool) := pure (Capnp.getBool r.struct 64)

def ModelGateway.info_Results.Reader.getSupportsVision (r : ModelGateway.info_Results.Reader) : Bool := Capnp.getBool r.struct 65
def ModelGateway.info_Results.Reader.getSupportsVisionChecked (r : ModelGateway.info_Results.Reader) : Except String (Bool) := pure (Capnp.getBool r.struct 65)
def ModelGateway.info_Results.initRoot : Capnp.BuilderM ModelGateway.info_Results.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 2 4
  return { struct := sb }

def ModelGateway.info_Results.Builder.clearModelId (b : ModelGateway.info_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ModelGateway.info_Results.Builder.setModelId (b : ModelGateway.info_Results.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 0) v

def ModelGateway.info_Results.Builder.clearSource (b : ModelGateway.info_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 1)

def ModelGateway.info_Results.Builder.setSource (b : ModelGateway.info_Results.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 1) v

def ModelGateway.info_Results.Builder.clearModelDir (b : ModelGateway.info_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 2)

def ModelGateway.info_Results.Builder.setModelDir (b : ModelGateway.info_Results.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 2) v

def ModelGateway.info_Results.Builder.clearDevice (b : ModelGateway.info_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 3)

def ModelGateway.info_Results.Builder.setDevice (b : ModelGateway.info_Results.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 3) v

def ModelGateway.info_Results.Builder.setMaxContextTokens (b : ModelGateway.info_Results.Builder) (v : UInt32) : Capnp.BuilderM Unit := do
  Capnp.setUInt32 b.struct 0 v

def ModelGateway.info_Results.Builder.setVocabSize (b : ModelGateway.info_Results.Builder) (v : UInt32) : Capnp.BuilderM Unit := do
  Capnp.setUInt32 b.struct 4 v

def ModelGateway.info_Results.Builder.setSupportsThinking (b : ModelGateway.info_Results.Builder) (v : Bool) : Capnp.BuilderM Unit := do
  Capnp.setBool b.struct 64 v

def ModelGateway.info_Results.Builder.setSupportsVision (b : ModelGateway.info_Results.Builder) (v : Bool) : Capnp.BuilderM Unit := do
  Capnp.setBool b.struct 65 v


def ModelGateway.generate_Params.Reader.getMessages (r : ModelGateway.generate_Params.Reader) : Capnp.ListReader ChatMessage.Reader := Capnp.ListReader.map ChatMessage.fromStruct (Capnp.readListStructReader (Capnp.getPointer r.struct 0))
def ModelGateway.generate_Params.Reader.getMessagesChecked (r : ModelGateway.generate_Params.Reader) : Except String (Capnp.ListReader ChatMessage.Reader) := do
  let r ← Capnp.readListStructCheckedReader (Capnp.getPointer r.struct 0)
  return Capnp.ListReader.map ChatMessage.fromStruct r
def ModelGateway.generate_Params.Reader.hasMessages (r : ModelGateway.generate_Params.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)


def ModelGateway.generate_Params.Reader.getMaxNewTokens (r : ModelGateway.generate_Params.Reader) : UInt32 := Capnp.getUInt32 r.struct 0
def ModelGateway.generate_Params.Reader.getMaxNewTokensChecked (r : ModelGateway.generate_Params.Reader) : Except String (UInt32) := pure (Capnp.getUInt32 r.struct 0)

def ModelGateway.generate_Params.Reader.getTemperature (r : ModelGateway.generate_Params.Reader) : Float := Capnp.getFloat32 r.struct 4
def ModelGateway.generate_Params.Reader.getTemperatureChecked (r : ModelGateway.generate_Params.Reader) : Except String (Float) := pure (Capnp.getFloat32 r.struct 4)

def ModelGateway.generate_Params.Reader.getTopK (r : ModelGateway.generate_Params.Reader) : UInt32 := Capnp.getUInt32 r.struct 8
def ModelGateway.generate_Params.Reader.getTopKChecked (r : ModelGateway.generate_Params.Reader) : Except String (UInt32) := pure (Capnp.getUInt32 r.struct 8)

def ModelGateway.generate_Params.Reader.getTopP (r : ModelGateway.generate_Params.Reader) : Float := Capnp.getFloat32 r.struct 12
def ModelGateway.generate_Params.Reader.getTopPChecked (r : ModelGateway.generate_Params.Reader) : Except String (Float) := pure (Capnp.getFloat32 r.struct 12)

def ModelGateway.generate_Params.Reader.getEnableThinking (r : ModelGateway.generate_Params.Reader) : Bool := Capnp.getBool r.struct 128
def ModelGateway.generate_Params.Reader.getEnableThinkingChecked (r : ModelGateway.generate_Params.Reader) : Except String (Bool) := pure (Capnp.getBool r.struct 128)
def ModelGateway.generate_Params.initRoot : Capnp.BuilderM ModelGateway.generate_Params.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 3 1
  return { struct := sb }

def ModelGateway.generate_Params.Builder.clearMessages (b : ModelGateway.generate_Params.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ModelGateway.generate_Params.Builder.initMessages (b : ModelGateway.generate_Params.Builder) (n : Nat) : Capnp.BuilderM (Array ChatMessage.Builder) := do
  let lb ← Capnp.initStructListPointer (Capnp.getPointerBuilder b.struct 0) 0 2 n
  return Array.map ChatMessage.Builder.fromStruct (Capnp.listStructBuilders lb)
def ModelGateway.generate_Params.Builder.setMessagesFromReaders (b : ModelGateway.generate_Params.Builder) (v : Array ChatMessage.Reader) : Capnp.BuilderM Unit := do
  let lb ← Capnp.initStructListPointer (Capnp.getPointerBuilder b.struct 0) 0 2 (v).size
  let builders := Capnp.listStructBuilders lb
  let emptySb : Capnp.StructBuilder :=
    { seg := 0, dataOff := 0, dataWords := 0, ptrOff := 0, ptrCount := 0 }
  let mut i_0 := 0
  for elem_1 in (v) do
    let sb := builders.getD i_0 emptySb
    Capnp.copyStruct sb elem_1.struct
    i_0 := i_0 + 1

def ModelGateway.generate_Params.Builder.setMaxNewTokens (b : ModelGateway.generate_Params.Builder) (v : UInt32) : Capnp.BuilderM Unit := do
  Capnp.setUInt32 b.struct 0 v

def ModelGateway.generate_Params.Builder.setTemperature (b : ModelGateway.generate_Params.Builder) (v : Float) : Capnp.BuilderM Unit := do
  Capnp.setFloat32 b.struct 4 v

def ModelGateway.generate_Params.Builder.setTopK (b : ModelGateway.generate_Params.Builder) (v : UInt32) : Capnp.BuilderM Unit := do
  Capnp.setUInt32 b.struct 8 v

def ModelGateway.generate_Params.Builder.setTopP (b : ModelGateway.generate_Params.Builder) (v : Float) : Capnp.BuilderM Unit := do
  Capnp.setFloat32 b.struct 12 v

def ModelGateway.generate_Params.Builder.setEnableThinking (b : ModelGateway.generate_Params.Builder) (v : Bool) : Capnp.BuilderM Unit := do
  Capnp.setBool b.struct 128 v


def ModelGateway.generate_Results.Reader.getText (r : ModelGateway.generate_Results.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 0)
def ModelGateway.generate_Results.Reader.getTextChecked (r : ModelGateway.generate_Results.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 0)
def ModelGateway.generate_Results.Reader.getTextView (r : ModelGateway.generate_Results.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 0)
def ModelGateway.generate_Results.Reader.getTextViewChecked (r : ModelGateway.generate_Results.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 0)

def ModelGateway.generate_Results.Reader.hasText (r : ModelGateway.generate_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)


def ModelGateway.generate_Results.Reader.getGeneratedTokens (r : ModelGateway.generate_Results.Reader) : Capnp.ListReader UInt32 := Capnp.readListUInt32Reader (Capnp.getPointer r.struct 1)
def ModelGateway.generate_Results.Reader.getGeneratedTokensChecked (r : ModelGateway.generate_Results.Reader) : Except String (Capnp.ListReader UInt32) := Capnp.readListUInt32CheckedReader (Capnp.getPointer r.struct 1)
def ModelGateway.generate_Results.Reader.hasGeneratedTokens (r : ModelGateway.generate_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 1)


def ModelGateway.generate_Results.Reader.getPromptTokenCount (r : ModelGateway.generate_Results.Reader) : UInt32 := Capnp.getUInt32 r.struct 0
def ModelGateway.generate_Results.Reader.getPromptTokenCountChecked (r : ModelGateway.generate_Results.Reader) : Except String (UInt32) := pure (Capnp.getUInt32 r.struct 0)

def ModelGateway.generate_Results.Reader.getGeneratedTokenCount (r : ModelGateway.generate_Results.Reader) : UInt32 := Capnp.getUInt32 r.struct 4
def ModelGateway.generate_Results.Reader.getGeneratedTokenCountChecked (r : ModelGateway.generate_Results.Reader) : Except String (UInt32) := pure (Capnp.getUInt32 r.struct 4)

def ModelGateway.generate_Results.Reader.getStopReason (r : ModelGateway.generate_Results.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 2)
def ModelGateway.generate_Results.Reader.getStopReasonChecked (r : ModelGateway.generate_Results.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 2)
def ModelGateway.generate_Results.Reader.getStopReasonView (r : ModelGateway.generate_Results.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 2)
def ModelGateway.generate_Results.Reader.getStopReasonViewChecked (r : ModelGateway.generate_Results.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 2)

def ModelGateway.generate_Results.Reader.hasStopReason (r : ModelGateway.generate_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 2)

def ModelGateway.generate_Results.initRoot : Capnp.BuilderM ModelGateway.generate_Results.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 1 3
  return { struct := sb }

def ModelGateway.generate_Results.Builder.clearText (b : ModelGateway.generate_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ModelGateway.generate_Results.Builder.setText (b : ModelGateway.generate_Results.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 0) v

def ModelGateway.generate_Results.Builder.clearGeneratedTokens (b : ModelGateway.generate_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 1)

def ModelGateway.generate_Results.Builder.initGeneratedTokens (b : ModelGateway.generate_Results.Builder) (n : Nat) : Capnp.BuilderM Capnp.ListBuilder := do
  Capnp.initListPointer (Capnp.getPointerBuilder b.struct 1) Capnp.elemSizeFourBytes n
def ModelGateway.generate_Results.Builder.setGeneratedTokens (b : ModelGateway.generate_Results.Builder) (v : Array UInt32) : Capnp.BuilderM Unit := do
  Capnp.writeListUInt32 (Capnp.getPointerBuilder b.struct 1) v

def ModelGateway.generate_Results.Builder.setPromptTokenCount (b : ModelGateway.generate_Results.Builder) (v : UInt32) : Capnp.BuilderM Unit := do
  Capnp.setUInt32 b.struct 0 v

def ModelGateway.generate_Results.Builder.setGeneratedTokenCount (b : ModelGateway.generate_Results.Builder) (v : UInt32) : Capnp.BuilderM Unit := do
  Capnp.setUInt32 b.struct 4 v

def ModelGateway.generate_Results.Builder.clearStopReason (b : ModelGateway.generate_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 2)

def ModelGateway.generate_Results.Builder.setStopReason (b : ModelGateway.generate_Results.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 2) v


def ModelGateway.tokenize_Params.Reader.getText (r : ModelGateway.tokenize_Params.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 0)
def ModelGateway.tokenize_Params.Reader.getTextChecked (r : ModelGateway.tokenize_Params.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 0)
def ModelGateway.tokenize_Params.Reader.getTextView (r : ModelGateway.tokenize_Params.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 0)
def ModelGateway.tokenize_Params.Reader.getTextViewChecked (r : ModelGateway.tokenize_Params.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 0)

def ModelGateway.tokenize_Params.Reader.hasText (r : ModelGateway.tokenize_Params.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)

def ModelGateway.tokenize_Params.initRoot : Capnp.BuilderM ModelGateway.tokenize_Params.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 0 1
  return { struct := sb }

def ModelGateway.tokenize_Params.Builder.clearText (b : ModelGateway.tokenize_Params.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ModelGateway.tokenize_Params.Builder.setText (b : ModelGateway.tokenize_Params.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 0) v


def ModelGateway.tokenize_Results.Reader.getTokens (r : ModelGateway.tokenize_Results.Reader) : Capnp.ListReader UInt32 := Capnp.readListUInt32Reader (Capnp.getPointer r.struct 0)
def ModelGateway.tokenize_Results.Reader.getTokensChecked (r : ModelGateway.tokenize_Results.Reader) : Except String (Capnp.ListReader UInt32) := Capnp.readListUInt32CheckedReader (Capnp.getPointer r.struct 0)
def ModelGateway.tokenize_Results.Reader.hasTokens (r : ModelGateway.tokenize_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)

def ModelGateway.tokenize_Results.initRoot : Capnp.BuilderM ModelGateway.tokenize_Results.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 0 1
  return { struct := sb }

def ModelGateway.tokenize_Results.Builder.clearTokens (b : ModelGateway.tokenize_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ModelGateway.tokenize_Results.Builder.initTokens (b : ModelGateway.tokenize_Results.Builder) (n : Nat) : Capnp.BuilderM Capnp.ListBuilder := do
  Capnp.initListPointer (Capnp.getPointerBuilder b.struct 0) Capnp.elemSizeFourBytes n
def ModelGateway.tokenize_Results.Builder.setTokens (b : ModelGateway.tokenize_Results.Builder) (v : Array UInt32) : Capnp.BuilderM Unit := do
  Capnp.writeListUInt32 (Capnp.getPointerBuilder b.struct 0) v


def ModelGateway.decode_Params.Reader.getTokens (r : ModelGateway.decode_Params.Reader) : Capnp.ListReader UInt32 := Capnp.readListUInt32Reader (Capnp.getPointer r.struct 0)
def ModelGateway.decode_Params.Reader.getTokensChecked (r : ModelGateway.decode_Params.Reader) : Except String (Capnp.ListReader UInt32) := Capnp.readListUInt32CheckedReader (Capnp.getPointer r.struct 0)
def ModelGateway.decode_Params.Reader.hasTokens (r : ModelGateway.decode_Params.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)

def ModelGateway.decode_Params.initRoot : Capnp.BuilderM ModelGateway.decode_Params.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 0 1
  return { struct := sb }

def ModelGateway.decode_Params.Builder.clearTokens (b : ModelGateway.decode_Params.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ModelGateway.decode_Params.Builder.initTokens (b : ModelGateway.decode_Params.Builder) (n : Nat) : Capnp.BuilderM Capnp.ListBuilder := do
  Capnp.initListPointer (Capnp.getPointerBuilder b.struct 0) Capnp.elemSizeFourBytes n
def ModelGateway.decode_Params.Builder.setTokens (b : ModelGateway.decode_Params.Builder) (v : Array UInt32) : Capnp.BuilderM Unit := do
  Capnp.writeListUInt32 (Capnp.getPointerBuilder b.struct 0) v


def ModelGateway.decode_Results.Reader.getText (r : ModelGateway.decode_Results.Reader) : Capnp.Text := Capnp.readText (Capnp.getPointer r.struct 0)
def ModelGateway.decode_Results.Reader.getTextChecked (r : ModelGateway.decode_Results.Reader) : Except String (Capnp.Text) := Capnp.readTextChecked (Capnp.getPointer r.struct 0)
def ModelGateway.decode_Results.Reader.getTextView (r : ModelGateway.decode_Results.Reader) : Capnp.TextView := Capnp.readTextView (Capnp.getPointer r.struct 0)
def ModelGateway.decode_Results.Reader.getTextViewChecked (r : ModelGateway.decode_Results.Reader) : Except String Capnp.TextView := Capnp.readTextViewChecked (Capnp.getPointer r.struct 0)

def ModelGateway.decode_Results.Reader.hasText (r : ModelGateway.decode_Results.Reader) : Bool := !Capnp.isNullPointer (Capnp.getPointer r.struct 0)

def ModelGateway.decode_Results.initRoot : Capnp.BuilderM ModelGateway.decode_Results.Builder := do
  let p ← Capnp.getRootPointer
  let sb ← Capnp.initStructPointer p 0 1
  return { struct := sb }

def ModelGateway.decode_Results.Builder.clearText (b : ModelGateway.decode_Results.Builder) : Capnp.BuilderM Unit := do
  Capnp.clearPointer (Capnp.getPointerBuilder b.struct 0)

def ModelGateway.decode_Results.Builder.setText (b : ModelGateway.decode_Results.Builder) (v : Capnp.Text) : Capnp.BuilderM Unit := do
  Capnp.writeText (Capnp.getPointerBuilder b.struct 0) v


mutual
  def ChatMessage.Builder.setFromValue (b : ChatMessage.Builder) (v : ChatMessage) : Capnp.BuilderM Unit := do
    b.setRole v.role
    b.setContent v.content


  def ModelGateway.info_Params.Builder.setFromValue (b : ModelGateway.info_Params.Builder) (v : ModelGateway.info_Params) : Capnp.BuilderM Unit := do
    let _ := b
    let _ := v
    pure ()


  def ModelGateway.info_Results.Builder.setFromValue (b : ModelGateway.info_Results.Builder) (v : ModelGateway.info_Results) : Capnp.BuilderM Unit := do
    b.setModelId v.modelId
    b.setSource v.source
    b.setModelDir v.modelDir
    b.setDevice v.device
    b.setMaxContextTokens v.maxContextTokens
    b.setVocabSize v.vocabSize
    b.setSupportsThinking v.supportsThinking
    b.setSupportsVision v.supportsVision


  def ModelGateway.generate_Params.Builder.setFromValue (b : ModelGateway.generate_Params.Builder) (v : ModelGateway.generate_Params) : Capnp.BuilderM Unit := do
    let lb ← Capnp.initStructListPointer (Capnp.getPointerBuilder b.struct 0) 0 2 (v.messages).size
    let builders := Capnp.listStructBuilders lb
    let emptySb : Capnp.StructBuilder :=
      { seg := 0, dataOff := 0, dataWords := 0, ptrOff := 0, ptrCount := 0 }
    let mut i_2 := 0
    for elem_3 in (v.messages) do
      let sb := builders.getD i_2 emptySb
      ChatMessage.Builder.setFromValue (ChatMessage.Builder.fromStruct sb) elem_3
      i_2 := i_2 + 1
    b.setMaxNewTokens v.maxNewTokens
    b.setTemperature v.temperature
    b.setTopK v.topK
    b.setTopP v.topP
    b.setEnableThinking v.enableThinking


  def ModelGateway.generate_Results.Builder.setFromValue (b : ModelGateway.generate_Results.Builder) (v : ModelGateway.generate_Results) : Capnp.BuilderM Unit := do
    b.setText v.text
    Capnp.writeListUInt32 (Capnp.getPointerBuilder b.struct 1) (v.generatedTokens)
    b.setPromptTokenCount v.promptTokenCount
    b.setGeneratedTokenCount v.generatedTokenCount
    b.setStopReason v.stopReason


  def ModelGateway.tokenize_Params.Builder.setFromValue (b : ModelGateway.tokenize_Params.Builder) (v : ModelGateway.tokenize_Params) : Capnp.BuilderM Unit := do
    b.setText v.text


  def ModelGateway.tokenize_Results.Builder.setFromValue (b : ModelGateway.tokenize_Results.Builder) (v : ModelGateway.tokenize_Results) : Capnp.BuilderM Unit := do
    Capnp.writeListUInt32 (Capnp.getPointerBuilder b.struct 0) (v.tokens)


  def ModelGateway.decode_Params.Builder.setFromValue (b : ModelGateway.decode_Params.Builder) (v : ModelGateway.decode_Params) : Capnp.BuilderM Unit := do
    Capnp.writeListUInt32 (Capnp.getPointerBuilder b.struct 0) (v.tokens)


  def ModelGateway.decode_Results.Builder.setFromValue (b : ModelGateway.decode_Results.Builder) (v : ModelGateway.decode_Results) : Capnp.BuilderM Unit := do
    b.setText v.text


end

def ModelGateway.generate_Params.Builder.setMessages (b : ModelGateway.generate_Params.Builder) (v : Array ChatMessage) : Capnp.BuilderM Unit := do
  let lb ← Capnp.initStructListPointer (Capnp.getPointerBuilder b.struct 0) 0 2 (v).size
  let builders := Capnp.listStructBuilders lb
  let emptySb : Capnp.StructBuilder :=
    { seg := 0, dataOff := 0, dataWords := 0, ptrOff := 0, ptrCount := 0 }
  let mut i_4 := 0
  for elem_5 in (v) do
    let sb := builders.getD i_4 emptySb
    ChatMessage.Builder.setFromValue (ChatMessage.Builder.fromStruct sb) elem_5
    i_4 := i_4 + 1



mutual
  def ChatMessage.ofReader (r : ChatMessage.Reader) : ChatMessage :=
    { role := r.getRole
    , content := r.getContent
    }


  def ModelGateway.info_Params.ofReader (_r : ModelGateway.info_Params.Reader) : ModelGateway.info_Params :=
    {
    }


  def ModelGateway.info_Results.ofReader (r : ModelGateway.info_Results.Reader) : ModelGateway.info_Results :=
    { modelId := r.getModelId
    , source := r.getSource
    , modelDir := r.getModelDir
    , device := r.getDevice
    , maxContextTokens := r.getMaxContextTokens
    , vocabSize := r.getVocabSize
    , supportsThinking := r.getSupportsThinking
    , supportsVision := r.getSupportsVision
    }


  def ModelGateway.generate_Params.ofReader (r : ModelGateway.generate_Params.Reader) : ModelGateway.generate_Params :=
    { messages := Capnp.ListReader.toArray (Capnp.ListReader.map (fun x => ChatMessage.ofReader x) (r.getMessages))
    , maxNewTokens := r.getMaxNewTokens
    , temperature := r.getTemperature
    , topK := r.getTopK
    , topP := r.getTopP
    , enableThinking := r.getEnableThinking
    }


  def ModelGateway.generate_Results.ofReader (r : ModelGateway.generate_Results.Reader) : ModelGateway.generate_Results :=
    { text := r.getText
    , generatedTokens := Capnp.ListReader.toArray (r.getGeneratedTokens)
    , promptTokenCount := r.getPromptTokenCount
    , generatedTokenCount := r.getGeneratedTokenCount
    , stopReason := r.getStopReason
    }


  def ModelGateway.tokenize_Params.ofReader (r : ModelGateway.tokenize_Params.Reader) : ModelGateway.tokenize_Params :=
    { text := r.getText
    }


  def ModelGateway.tokenize_Results.ofReader (r : ModelGateway.tokenize_Results.Reader) : ModelGateway.tokenize_Results :=
    { tokens := Capnp.ListReader.toArray (r.getTokens)
    }


  def ModelGateway.decode_Params.ofReader (r : ModelGateway.decode_Params.Reader) : ModelGateway.decode_Params :=
    { tokens := Capnp.ListReader.toArray (r.getTokens)
    }


  def ModelGateway.decode_Results.ofReader (r : ModelGateway.decode_Results.Reader) : ModelGateway.decode_Results :=
    { text := r.getText
    }


end

end TyrModelServer.Capnp.model_gateway
